[project]
name = "deep-learning-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "image>=1.5.33",
    "matplot>=0.1.9",
    "numpy>=2.4.0",
]
